[package]
name = "dirman"
version = "0.1.0"
authors = ["Alex Snezhko <alexsnezhko89@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.11.3"
chrono = "0.4"
